{
 "title": "Screep",
 "tags": [ "Screeps" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Game Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard3.gameTime" }
   ]
  },
  {
   "title": "Credits",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard3.credits" }
   ]
  },
  {
   "title": "Global Control Level Progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "targets": [
    { "target": "screeps.planc.shard3.gcl" }
   ]
  },
  {
   "title": "CPU Usage & Bucket",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "CPU Usage" }
   ],
   "targets": [
    { "target": "screeps.planc.shard3.cpu" },
    { "target": "screeps.planc.shard3.bucket" }
   ]
  },
  {
   "title": "Market",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Credits" }
   ],
   "targets": [
    {
     "target": "screeps.planc.shard3.valueEnergy"
    },
    {
     "target": "screeps.planc.shard3.valueUtrium"
    },
    {
     "target": "screeps.planc.shard3.valueToken"
    }
   ]
  },
  {
   "title": "Global Power Level Progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "targets": [
    { "target": "screeps.planc.shard3.gpl" }
   ]
  },
  {
   "title": "Global Control Level",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard3.gclLevel" }
   ]
  },
  {
   "title": "Global Power Level",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard3.gplLevel" }
   ]
  },
  {
   "title": "W34N2 Resource Statues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Storage" }
   ],
   "targets": [
    {
     "target": "screeps.planc.shard3.storageW34N2"
    },
    {
     "target": "screeps.planc.shard3.terminalW34N2"
    }
   ]
  },
  {
   "title": "W34N3 Resource Statues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Storage" }
   ],
   "targets": [
    {
     "target": "screeps.planc.shard3.storageW34N3"
    },
    {
     "target": "screeps.planc.shard3.terminalW34N3"
    }
   ]
  },
  {
   "title": "Game Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard3.gameTime" }
   ]
  },
  {
   "title": "Credits",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard3.credits" }
   ]
  }
 ]
}